---

- name: known hosts - global
  known_hosts:
    path='/etc/ssh/ssh_known_hosts'
    name={{ item }}
    key="{{ lookup('pipe', 'ssh-keyscan -H -t rsa ' + item) }}"
  with_items: sshkey_known_hosts_global
  become_user: root

