---

- name: create user
  include: user.yml
  when: sshkey_create_user

- name: deploy keys
  include: keys.yml

- name: known hosts
  include: known-hosts.yml

- name: profile
  include: profile.yml
